---
openbao_backup_primary_node: bao-1
openbao_backup_local_dir: /var/lib/openbao/snapshots
openbao_backup_script_path: /usr/local/sbin/openbao-raft-backup
openbao_backup_hour: "02"
openbao_backup_minute: "15"
