#!/usr/bin/env python3
"""Generate the reference tables that must never go stale (Phase 5).

Writes docs/reference/generated/*.md from the repository itself:
  counts.md        components, playbooks, roles, tests, workflows, guests, ...
  versions.md      every pinned version (tools, providers, collections, images, pip)
  make-targets.md  every Make target with its help text
  workflows.md     every workflow: triggers, jobs, runner, environment
  gates.md         every approval gate: flag, confirmation variable, expected value
  backups.md       every stateful item from docs/reference/backup-matrix.yml

Usage: generate_reference.py            write the files
       generate_reference.py --check    exit 1 if any file is out of date
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "reference" / "generated"
HEADER = "<!-- Generated by tools/docs/generate_reference.py; do not edit. Run `make docs-reference`. -->\n\n"
SKIP = ("public/", "services/music-library/")


def tracked() -> list[str]:
    out = subprocess.run(["git", "-C", str(ROOT), "ls-files"], check=True, capture_output=True, text=True)
    return [p for p in out.stdout.splitlines() if not p.startswith(SKIP) and (ROOT / p).is_file()]


def makefiles(files: list[str]) -> list[str]:
    return sorted(f for f in files if Path(f).name == "Makefile")


def table(header: list[str], rows: list[list[str]]) -> str:
    def cell(value: str) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")

    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join("---" for _ in header) + " |"]
    lines += ["| " + " | ".join(cell(v) for v in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def load_yaml(rel: str):
    try:
        return yaml.safe_load((ROOT / rel).read_text(encoding="utf-8"))
    except yaml.YAMLError:
        return None


# --------------------------------------------------------------------------- counts
def counts(files: list[str]) -> str:
    lab = load_yaml("inventory/lab.yml")
    playbooks = [f for f in files if "/ansible/playbooks/" in f and f.endswith(".yml")]
    roles = {f.split("/roles/")[1].split("/")[0] for f in files if "/ansible/roles/" in f}
    tests = sum(
        len(re.findall(r"^def test_", (ROOT / f).read_text(encoding="utf-8"), re.M))
        for f in files
        if re.search(r"(^|/)test_[^/]+\.py$", f)
    )
    tofu_tests = sum(
        len(re.findall(r'^run "', (ROOT / f).read_text(encoding="utf-8"), re.M))
        for f in files
        if f.endswith(".tftest.hcl")
    )
    rows = [
        ["Components with a Makefile", len([m for m in makefiles(files) if "/" in m])],
        ["Ansible playbooks", len(playbooks)],
        ["Ansible roles", len(roles)],
        ["OpenTofu roots", len({str(Path(f).parent) for f in files if f.endswith("/versions.tf")})],
        ["Python test functions (before parametrisation)", tests],
        ["OpenTofu test runs (mocked providers)", tofu_tests],
        ["GitHub Actions workflows", len([f for f in files if f.startswith(".github/workflows/")])],
        ["Architecture decision records", len([f for f in files if f.startswith("docs/decisions/ADR-")])],
        [
            "Agent skills",
            len([f for f in files if f.startswith(".agents/skills/") and f.endswith("SKILL.md")]),
        ],
        ["Walkthrough diagrams", len([f for f in files if f.endswith(".mmd")])],
        ["Proxmox nodes (lab.yml)", len(lab["nodes"])],
        ["Guests (lab.yml)", len(lab["guests"])],
        ["Scheduled vzdump jobs (lab.yml)", len(lab["backup_jobs"])],
    ]
    return HEADER + "# Repository counts\n\n" + table(["Item", "Count"], rows)


# --------------------------------------------------------------------------- versions
def versions(files: list[str]) -> str:
    rows: list[list[str]] = []
    dockerfile = (ROOT / ".devcontainer/Dockerfile").read_text(encoding="utf-8")
    for name, value in re.findall(r"^ARG ([A-Z_]+_VERSION)=(\S+)", dockerfile, re.M):
        rows.append(
            [
                "devcontainer",
                name.removesuffix("_VERSION").lower().replace("_", "-"),
                value,
                ".devcontainer/Dockerfile",
            ]
        )
    for f in [f for f in files if f.endswith("versions.tf")]:
        text = (ROOT / f).read_text(encoding="utf-8")
        for source, version in re.findall(r'source\s*=\s*"([^"]+)"\s*\n\s*version\s*=\s*"([^"]+)"', text):
            rows.append(["OpenTofu provider", source, version, f])
    for f in [f for f in files if Path(f).name == "requirements.yml"]:
        data = load_yaml(f) or {}
        for coll in data.get("collections") or []:
            rows.append(["Galaxy collection", coll["name"], str(coll.get("version", "")), f])
    for f in [f for f in files if re.search(r"(^|/)compose\.ya?ml$", f)]:
        for image in re.findall(r"^\s*image:\s*(\S+)", (ROOT / f).read_text(encoding="utf-8"), re.M):
            name, _, digest = image.partition("@")
            short = f"{digest[:19]}…" if digest else "(no digest)"
            rows.append(["Container image", name, short, f])
    for f in [f for f in files if Path(f).name.startswith("requirements") and f.endswith(".txt")]:
        for line in (ROOT / f).read_text(encoding="utf-8").splitlines():
            match = re.match(r"^([A-Za-z0-9_.\-\[\]]+)\s*(==|>=)\s*([^\s#;,]+)", line)
            if match:
                rows.append(["Python package", match.group(1), match.group(2) + match.group(3), f])
    rows.sort(key=lambda r: (r[0], r[1].lower(), r[3]))
    return HEADER + "# Version matrix\n\n" + table(["Kind", "Name", "Pinned", "Source"], rows)


# --------------------------------------------------------------------------- make targets
TARGET = re.compile(r"^([A-Za-z0-9_.-]+):(?!=)[^#\n]*?(?:##\s*(.*))?$", re.M)


def make_targets(files: list[str]) -> str:
    out = [HEADER + "# Make targets\n"]
    for makefile in makefiles(files):
        text = (ROOT / makefile).read_text(encoding="utf-8")
        rows = []
        for name, help_text in TARGET.findall(text):
            if name.startswith(".") or name in {"define", "endef"}:
                continue
            help_text = re.sub(r"(https?://\S+)", r"`\1`", help_text.strip())  # no bare URLs
            rows.append([f"`{name}`", help_text or "—"])
        if rows:
            directory = str(Path(makefile).parent)
            title = "repository root" if directory == "." else f"`{directory}`"
            out.append(f"\n## {title}\n\n" + table(["Target", "What it does"], rows))
    return "".join(out)


# --------------------------------------------------------------------------- workflows
def workflows(files: list[str]) -> str:
    rows = []
    for f in sorted(x for x in files if x.startswith(".github/workflows/")):
        doc = load_yaml(f) or {}
        on = doc.get("on", doc.get(True))
        events = ", ".join(on if isinstance(on, list) else [on] if isinstance(on, str) else list(on or {}))
        for job_name, job in (doc.get("jobs") or {}).items():
            runs_on = job.get("runs-on", "reusable" if "uses" in job else "")
            runs_on = ", ".join(runs_on) if isinstance(runs_on, list) else str(runs_on)
            rows.append([f"`{Path(f).name}`", events, f"`{job_name}`", runs_on, job.get("environment", "—")])
    return HEADER + "# Workflows\n\n" + table(["Workflow", "Triggers", "Job", "Runner", "Environment"], rows)


# --------------------------------------------------------------------------- gates
def _asserts(node):
    if isinstance(node, dict):
        for key, value in node.items():
            if key in ("ansible.builtin.assert", "assert") and isinstance(value, dict):
                yield value.get("that") or []
            else:
                yield from _asserts(value)
    elif isinstance(node, list):
        for item in node:
            yield from _asserts(item)


def _set_facts(node):
    if isinstance(node, dict):
        for key, value in node.items():
            if key in ("ansible.builtin.set_fact", "set_fact") and isinstance(value, dict):
                yield from ((k, v) for k, v in value.items() if isinstance(v, str))
            else:
                yield from _set_facts(value)
    elif isinstance(node, list):
        for item in node:
            yield from _set_facts(item)


def _variables(files: list[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    for f in files:
        if not f.endswith(".yml"):
            continue
        if "/defaults/" in f or "group_vars" in f:
            data = load_yaml(f)
            if isinstance(data, dict):
                values.update({k: v for k, v in data.items() if isinstance(v, str)})
        elif "/ansible/" in f:
            values.update(dict(_set_facts(load_yaml(f))))
    return values


def _expected(expression: str, values: dict[str, str]) -> str:
    literal = values.get(expression, expression).strip()
    if literal in {"SET-ME", ""}:
        return f"set per stage by the calling playbook (`{expression}`)"
    return literal.strip("\"'") if re.fullmatch(r"([\"']).*\1", literal) else literal


def gates(files: list[str]) -> str:
    values = _variables(files)
    rows = []
    sources = [f for f in files if f.endswith(".yml") and ("/ansible/" in f or f.startswith("inventory/"))]
    for f in sorted(sources):
        for that in _asserts(load_yaml(f)):
            items = [str(x).strip() for x in (that if isinstance(that, list) else [that])]
            flags = [m.group(1) for x in items if (m := re.fullmatch(r"(\w*allow\w*) \| bool", x))]
            confirms = [
                (m.group(1), m.group(2).strip())
                for x in items
                if (m := re.fullmatch(r"(\w*confirmation\w*) == (.+)", x))
            ]
            if not flags and not confirms:
                continue
            for index in range(max(len(flags), len(confirms))):
                flag = flags[index] if index < len(flags) else "—"
                var, expected = confirms[index] if index < len(confirms) else ("—", "flag only")
                shown = expected if expected == "flag only" else _expected(expected, values)
                rows.append([f"`{flag}`", f"`{var}`", shown, f"`{f}`"])
    unique = sorted({tuple(r) for r in rows}, key=lambda r: (r[3], r[0]))
    note = (
        'Every gate defaults the flag to `false` and the confirmation to `""`. Expressions using '
        "`inventory_hostname` are filled in with the target host.\n\n"
    )
    return (
        HEADER
        + "# Approval gates\n\n"
        + note
        + table(
            ["Flag", "Confirmation variable", "Expected confirmation", "Asserted in"],
            [list(r) for r in unique],
        )
    )


# --------------------------------------------------------------------------- backups
def backups(files: list[str]) -> str:
    items = load_yaml("docs/reference/backup-matrix.yml")["items"]
    rows = [
        [i["id"], i["what"], i["schedule"], i["destination"], i["restore"], i["verify"], i["status"]]
        for i in items
    ]
    note = "Rendered from `docs/reference/backup-matrix.yml`; edit that file, then run `make docs-reference`.\n\n"
    return (
        HEADER
        + "# Backup and restore matrix\n\n"
        + note
        + table(["Item", "What", "Schedule", "Destination", "Restore", "Verify", "Status"], rows)
    )


GENERATORS = {
    "counts.md": counts,
    "versions.md": versions,
    "make-targets.md": make_targets,
    "workflows.md": workflows,
    "gates.md": gates,
    "backups.md": backups,
}


def render_all() -> dict[str, str]:
    files = tracked()
    return {name: fn(files) for name, fn in GENERATORS.items()}


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rendered = render_all()
    stale = []
    for name, text in rendered.items():
        path = OUT / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            OUT.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        print("out of date (run make docs-reference): " + ", ".join(stale))
        return 1
    print("generated reference is " + ("up to date" if args.check else f"written to {OUT.relative_to(ROOT)}"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
