---
openbao_tls_ca_source: "{{ openbao_tls_controller_root }}/ca.pem"
openbao_tls_cert_source: "{{ openbao_tls_controller_root }}/{{ inventory_hostname }}.pem"
openbao_tls_key_source: "{{ openbao_tls_controller_root }}/{{ inventory_hostname }}-key.pem"
