---
- name: Restart OpenBao
  ansible.builtin.systemd_service:
    name: openbao
    state: restarted
    daemon_reload: true

- name: Restart HAProxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted

- name: Restart Keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
