---
openbao_server_release_base: "https://github.com/openbao/openbao/releases/download/v{{ openbao_version }}"
openbao_server_archive: "openbao_{{ openbao_version }}_linux_amd64.tar.gz"
openbao_server_download_dir: "/var/cache/openbao/{{ openbao_version }}"
