---
openbao_host_packages:
  - age
  - ca-certificates
  - chrony
  - curl
  - gnupg
  - haproxy
  - jq
  - keepalived
  - logrotate
  - qemu-guest-agent
  - rsync
  - unattended-upgrades
  - unzip
  - ufw
